### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mml1** [b1llfantast1c/colmar-academy#3]
[Exceeds Expectations] Brilliant work!

**Great:**
- media queries
- responsive design
- rem usage
- descriptive comments
- flex-box usage
- onHover animations
- alt tags on images
- project structure
- Relative links
- consistent indentation
- consistent spacing

**Suggested improvements:**

- You have unused code at the following lines:
https://github.com/b1llfantast1c/colmar-academy/blob/master/resources/css/style.css#L79-L81

Overall, you have grasped the fundamentals and have gone beyond them. You are on 🔥. 

Great work 👍 .

**Comment by b1llfantast1c** [comment]
Thank you, I felt like it was getting easier.  Can't wait to try some more challenging coding.
